version: '3.8'

services:

  provider:
    container_name: provider
    build:
      context: ../launcher
    environment:
      IDS_WEBHOOK_ADDRESS: http://provider:8282
      EDC_IDENTITY_DID_URL: did:web:didserver:provider
      EDC_VAULT_NAME: ${PROVIDER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
      EDC_API_AUTH_KEY: sekrit
      NODES_JSON_FILES_PREFIX: registry-
      NODES_JSON_DIR: /resources
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 1
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 1
    ports:
      - "9191:9191"
      - "8181:8181"
    volumes:
      - ./resources:/resources

  consumer:
    container_name: consumer
    build:
      context: ../launcher
    environment:
      IDS_WEBHOOK_ADDRESS: http://consumer:8282
      EDC_IDENTITY_DID_URL: did:web:didserver:consumer
      EDC_VAULT_NAME: ${CONSUMER_KEY_VAULT}
      EDC_VAULT_TENANTID: ${EDC_VAULT_TENANTID}
      EDC_VAULT_CLIENTID: ${EDC_VAULT_CLIENTID}
      EDC_VAULT_CLIENTSECRET: ${EDC_VAULT_CLIENTSECRET}
      EDC_API_AUTH_KEY: sekrit
      NODES_JSON_FILES_PREFIX: registry-
      NODES_JSON_DIR: /resources
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 1
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 1
    ports:
      - "9192:9191"
      - "8182:8181"
    volumes:
      - ./resources:/resources

  didserver:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./resources/did:/usr/share/nginx/html