@startuml
autonumber "<b>0'.'"
box "Company1" #LightBlue
Participant Company1
Participant "Company1\nDID Document &\nSelf-description\nDocument" as DID1
Participant "Company1\nIdentity Hub" as IDHUB1
end box
box "Dataspace Authority" #LightYellow
Participant "Dataspace\nDID Document" as DID0
Participant "Dataspace\nSelf-description\nDocument" as SDD0
Participant "DA\nIdentity Hub" as IDHUB0
Participant "DA API" as DA
Database "Participant\nRegistry" as Registry
Database "Certificate\nLog" as CertLog
end box

Company1 -> DID0: Get SDD URL
Company1 -> SDD0: Get enrollment endpoint
Company1 -> DA ++: Call enrollment endpoint:\n - DID JWS\n - Hub Token
group authorize request [Distributed authorization sub-flow]
  DA -> DID1
  DA -> IDHUB1
end
DA -> DA: apply enrollment policy
DA -> Registry: Store membership
DA -> DA: Sign membership certificate
DA -> CertLog: Store certificate
DA -> IDHUB1 ++: signed membership credential:\n - Hub Token
IDHUB1 -> IDHUB1: Store membership credential

@enduml