name: Checks

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  Checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Terraform files are properly formatted (run "terraform fmt -recursive" to fix)
        run: |
          terraform fmt -recursive
          git diff --exit-code
